// frontend-react/src/components/VideoUpload.tsx
// Upload a recorded event video and watch SnapAI process it frame-by-frame.
// Works in both User and Developer mode; styles adapt to the parent theme.

import { useEffect, useRef, useState } from "react";
import { Upload, FileVideo, CheckCircle2, AlertTriangle,
         Loader2, Sparkles, Images } from "lucide-react";
import { Sessions } from "@/api/client";
import { useSession } from "@/store/session";
import { ReviewPanel } from "./ReviewPanel";
import { AlbumReview } from "./AlbumReview";

type Phase = "idle" | "uploading" | "processing" | "done" | "error";

// A poll failing once is normal (a blip). A poll failing for this long in a
// row on a phone usually means WiFi dropped or the tab got backgrounded —
// without this, the old code retried forever in total silence and the user
// just saw a frozen progress bar with no way to tell "still working" from
// "dead". The upload keeps processing server-side regardless of the
// client's connection, so we never abandon the poll — just say so.
const POLL_STALE_MS = 8000;

/** Curated-album summary returned by /video_progress once status==="done". */
interface AlbumSummary {
  event_name: string; total_selected: number;
  total_captured: number; cover: string; stats?: any;
}

interface Props {
  /** When true, render the dark "developer" theme variant. */
  dark?: boolean;
  /** Optional — collapse the card by default; useful in DevMode side panels. */
  defaultCollapsed?: boolean;
}

export function VideoUpload({ dark = false, defaultCollapsed = false }: Props) {
  const sid = useSession((s) => s.sid);
  const setUploading = useSession((s) => s.setUploading);
  const [file, setFile] = useState<File | null>(null);
  const [sampleFps, setSampleFps] = useState<number>(2.0);
  const [phase, setPhase] = useState<Phase>("idle");
  const [uploadPct, setUploadPct] = useState(0);
  const [progressPct, setProgressPct] = useState(0);
  const [frames, setFrames] = useState({ done: 0, total: 0, caps: 0 });
  const [error, setError] = useState<string | null>(null);
  const [collapsed, setCollapsed] = useState(defaultCollapsed);
  // See POLL_STALE_MS — surfaces "still trying to reach the server" instead
  // of a silently-frozen progress bar.
  const [connLost, setConnLost] = useState(false);
  const lastPollOkRef = useRef(Date.now());

  // Album auto-generated by the backend when a recorded video finishes.
  const [album, setAlbum] = useState<AlbumSummary | null>(null);
  const [albumPhotos, setAlbumPhotos] = useState<any[] | null>(null);
  const [albumLoading, setAlbumLoading] = useState(false);

  const pollRef = useRef<number | null>(null);
  // Each upload runs in its OWN fresh session id, held here — NOT in the shared
  // store, so changing it can't trigger the [sid] reset effect mid-upload and
  // so it's fully isolated from live mode and from any other user's session.
  const uploadSidRef = useRef<string | null>(null);

  // ── Cleanup poll on unmount ───────────────────────────────────────
  useEffect(() => () => {
    if (pollRef.current !== null) {
      clearInterval(pollRef.current); pollRef.current = null;
    }
  }, []);

  // ── Reset state when session changes ──────────────────────────────
  useEffect(() => {
    setPhase("idle"); setFile(null); setUploadPct(0); setProgressPct(0);
    setFrames({ done: 0, total: 0, caps: 0 }); setError(null);
    setAlbum(null); setAlbumPhotos(null); setAlbumLoading(false);
    setConnLost(false);
    if (pollRef.current !== null) {
      clearInterval(pollRef.current); pollRef.current = null;
    }
  }, [sid]);

  // ── File picker handler ───────────────────────────────────────────
  const onPick = (f: File | null) => {
    if (!f) return;
    if (!f.type.startsWith("video/") && !/\.(mp4|mov|webm|mkv|avi)$/i.test(f.name)) {
      setError(`Not a video file: ${f.name}`); return;
    }
    setFile(f); setError(null); setPhase("idle");
    setUploadPct(0); setProgressPct(0);
    setFrames({ done: 0, total: 0, caps: 0 });
  };

  // ── Upload + poll progress ────────────────────────────────────────
  const upload = async () => {
    if (!file) { setError("Pick a video first"); return; }
    setError(null); setAlbum(null); setAlbumPhotos(null);
    setPhase("uploading"); setUploadPct(0);
    setUploading(true);    // pause the live camera so it doesn't mix captures
    try {
      // FRESH SESSION PER UPLOAD. Each clip gets its own brand-new session, so
      // two clips can never share pipeline state or an album — this is what
      // stops "I uploaded clip A but clip B's result showed up". Kept in a ref
      // (not the store), so it never trips the [sid] reset effect and stays
      // isolated from live mode and from every other user on the same server.
      const st = useSession.getState();
      const priorUpload = uploadSidRef.current;
      if (priorUpload) Sessions.end(priorUpload).catch(() => {});
      const created = await Sessions.create(
        st.eventName || "birthday", st.eventType || "birthday",
        st.prompt || st.eventType || "birthday");
      const upSid = created.session_id;
      uploadSidRef.current = upSid;

      await Sessions.uploadVideo(upSid, file, sampleFps, (loaded, total) => {
        setUploadPct(Math.round((loaded / total) * 100));
      });
      setPhase("processing");
      lastPollOkRef.current = Date.now(); setConnLost(false);
      // Start polling THIS upload's own session id.
      pollRef.current = window.setInterval(async () => {
        try {
          const p = await Sessions.videoProgress(upSid);
          lastPollOkRef.current = Date.now();
          setConnLost(false);              // any successful poll clears it
          setProgressPct(p.progress);
          setFrames({
            done: p.processed_frames, total: p.total_frames, caps: p.captures
          });
          if (p.status === "done") {
            setAlbum(p.album ?? null);   // backend auto-built the album
            setPhase("done"); setUploading(false);   // resume live camera
            if (pollRef.current !== null) {
              clearInterval(pollRef.current); pollRef.current = null;
            }
          } else if (p.status === "error") {
            setPhase("error"); setError(p.error || "Server reported error");
            setUploading(false);
            if (pollRef.current !== null) {
              clearInterval(pollRef.current); pollRef.current = null;
            }
          }
        } catch {
          // Keep retrying forever — the video is still processing
          // server-side regardless of whether THIS phone can reach it right
          // now. Only difference from before: say so once it's been long
          // enough that "transient blip" no longer explains it.
          if (Date.now() - lastPollOkRef.current > POLL_STALE_MS) setConnLost(true);
        }
      }, 800);
    } catch (e: any) {
      setPhase("error"); setError(e?.message ?? String(e)); setUploading(false);
    }
  };

  // ── Album viewer ────────────────────────────────────────────────────
  // The backend already generated + saved the album on completion; this
  // just fetches the curated photo list so we can show it inline.
  const viewAlbum = async () => {
    const aSid = uploadSidRef.current || sid;   // THIS upload's session, not live
    if (!aSid) return;
    setAlbumLoading(true);
    try {
      const a = await Sessions.album(aSid);
      setAlbumPhotos(a.photos ?? []);
      if (a) setAlbum({
        event_name: a.event_name, total_selected: a.total_selected,
        total_captured: a.total_captured, cover: a.cover, stats: a.stats,
      });
    } catch (e: any) {
      setError(e?.message ?? "Could not load album");
    } finally {
      setAlbumLoading(false);
    }
  };

  const startOver = () => {
    setPhase("idle"); setFile(null);
    setAlbum(null); setAlbumPhotos(null); setConnLost(false);
  };

  // ── Drag-and-drop ──────────────────────────────────────────────────
  const [dragOver, setDragOver] = useState(false);
  const dragProps = {
    onDragOver: (e: React.DragEvent) => {
      e.preventDefault(); setDragOver(true);
    },
    onDragLeave: () => setDragOver(false),
    onDrop: (e: React.DragEvent) => {
      e.preventDefault(); setDragOver(false);
      const f = e.dataTransfer?.files?.[0];
      if (f) onPick(f);
    },
  };

  // ── Theme classes ──────────────────────────────────────────────────
  const cardCls = dark
    ? "rounded-lg bg-ink-800 border border-ink-700 text-slate-200"
    : "rounded-2xl bg-white border border-slate-100 shadow-sm";
  const subTextCls = dark ? "text-slate-400" : "text-slate-500";
  const inputCls = dark
    ? "bg-ink-700 border-ink-700 text-slate-100"
    : "bg-white border-slate-200 text-ink-900";

  // ── Collapsed pill (for DevMode side panels) ──────────────────────
  if (collapsed) {
    return (
      <button onClick={() => setCollapsed(false)}
        className={"w-full text-left px-4 py-3 flex items-center gap-2 " +
                   "transition hover:opacity-90 " + cardCls}>
        <FileVideo className="w-4 h-4" />
        <span className="text-sm font-medium">Upload a video instead</span>
        <span className={"ml-auto text-xs " + subTextCls}>click to expand</span>
      </button>
    );
  }

  // ── Main card ──────────────────────────────────────────────────────
  return (
    <div className={"p-5 " + cardCls}>
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <FileVideo className={"w-4 h-4 " + (dark ? "text-brand-500" : "text-brand-600")} />
          <h3 className="font-semibold">Analyze a video</h3>
        </div>
        {defaultCollapsed && (
          <button onClick={() => setCollapsed(true)}
            className={"text-xs " + subTextCls + " hover:underline"}>
            collapse
          </button>
        )}
      </div>

      {/* Drop zone */}
      {phase === "idle" && (
        <>
          <label {...dragProps}
            className={"block border-2 border-dashed rounded-xl px-5 py-8 " +
                       "text-center cursor-pointer transition " +
                       (dragOver
                         ? (dark ? "border-brand-500 bg-ink-700"
                                 : "border-brand-500 bg-brand-50")
                         : (dark ? "border-ink-700 hover:border-ink-600"
                                 : "border-slate-200 hover:border-brand-400"))}>
            <input type="file" accept="video/*" className="hidden"
              onChange={(e) => onPick(e.target.files?.[0] ?? null)} />
            <Upload className={"w-7 h-7 mx-auto mb-2 " + subTextCls} />
            <div className="text-sm font-medium">
              {file ? file.name : "Drop a video here, or click to pick"}
            </div>
            <div className={"text-xs mt-1 " + subTextCls}>
              {file
                ? `${(file.size / 1024 / 1024).toFixed(1)} MB`
                : "MP4 / MOV / WEBM · up to 100 MB recommended"}
            </div>
          </label>

          {/* Sample-rate slider */}
          <div className="mt-4">
            <div className="flex items-baseline justify-between mb-1.5 text-sm">
              <span className={"font-medium " + (dark ? "text-slate-200" : "text-ink-900")}>
                Sample rate
              </span>
              <span className={"font-mono " + subTextCls}>
                {sampleFps.toFixed(1)} fps
              </span>
            </div>
            <input type="range" min={0.5} max={10} step={0.5}
              value={sampleFps}
              onChange={(e) => setSampleFps(parseFloat(e.target.value))}
              className="w-full accent-brand-500" />
            <div className={"flex justify-between text-[10px] mt-1 " + subTextCls}>
              <span>0.5 fps · fast preview</span>
              <span>10 fps · maximum detail</span>
            </div>
          </div>

          {/* Action */}
          <button onClick={upload} disabled={!file || !sid}
            className={"mt-5 w-full py-3 rounded-xl font-semibold transition " +
                       "disabled:opacity-40 disabled:cursor-not-allowed " +
                       "bg-gradient-to-br from-brand-500 to-brand-700 " +
                       "text-white shadow hover:shadow-lg hover:-translate-y-0.5"}>
            <span className="flex items-center justify-center gap-2">
              <Sparkles className="w-4 h-4" />
              Analyze video
            </span>
          </button>

          {error && (
            <div className="mt-3 px-3 py-2 rounded-lg bg-rose-50 border border-rose-200
                            text-rose-700 text-xs flex items-start gap-2">
              <AlertTriangle className="w-4 h-4 shrink-0 mt-0.5" />
              <span>{error}</span>
            </div>
          )}
        </>
      )}

      {/* Uploading */}
      {phase === "uploading" && (
        <UploadProgress
          label="Uploading…"
          subtitle={`${file?.name} · ${(file!.size / 1024 / 1024).toFixed(1)} MB`}
          pct={uploadPct} dark={dark} />
      )}

      {/* Processing */}
      {phase === "processing" && (
        <>
          <UploadProgress
            label="Analyzing frames…"
            subtitle={frames.total > 0
              ? `Frame ${frames.done} / ${frames.total} · ${frames.caps} moments captured`
              : "Starting…"}
            pct={progressPct} dark={dark} />
          {connLost && (
            <div className="mt-3 px-3 py-2 rounded-lg bg-amber-50 border border-amber-200
                            text-amber-700 text-xs flex items-start gap-2">
              <AlertTriangle className="w-4 h-4 shrink-0 mt-0.5" />
              <span>Having trouble reaching the server — check your connection.
                Your video keeps processing either way; this will update the
                moment we reconnect.</span>
            </div>
          )}
        </>
      )}

      {/* Done */}
      {phase === "done" && (
        <div className="py-3">
          <div className="text-center">
            <CheckCircle2 className="w-12 h-12 mx-auto mb-3 text-emerald-500" />
            <div className={"font-semibold " + (dark ? "text-slate-100" : "text-ink-900")}>
              Captured {frames.caps} moment{frames.caps === 1 ? "" : "s"}
            </div>
            <div className={"text-sm mt-1 " + subTextCls}>
              From {frames.done} frames of {file?.name}
            </div>
          </div>

          {/* Auto-generated album summary (session has ended) */}
          {album && (
            <div className={"mt-4 px-4 py-3 rounded-xl text-sm " +
              (dark ? "bg-ink-700/60 border border-ink-700"
                    : "bg-brand-50 border border-brand-100")}>
              <div className="flex items-center gap-2 font-medium">
                <Images className="w-4 h-4 text-brand-500" />
                Album ready · {album.total_selected} best of {album.total_captured}
              </div>
              <div className={"mt-1 " + subTextCls}>
                Saved as <span className="font-mono">{album.event_name}</span>.
                Session ended automatically.
              </div>
            </div>
          )}

          {/* Curated album with per-photo reactions + overall review */}
          {albumPhotos && albumPhotos.length > 0 && sid && (
            <AlbumReview sessionId={sid} photos={albumPhotos} />
          )}
          {albumPhotos && albumPhotos.length === 0 && (
            <div className={"mt-3 text-center text-sm " + subTextCls}>
              No photos passed album curation.
            </div>
          )}

          {/* Actions */}
          <div className="mt-4 flex items-center justify-center gap-2">
            {frames.caps > 0 && !albumPhotos && (
              <button onClick={viewAlbum} disabled={albumLoading}
                className={"px-4 py-2 rounded-lg text-sm font-medium transition " +
                  "disabled:opacity-50 text-white " +
                  "bg-gradient-to-br from-brand-500 to-brand-700 " +
                  "hover:shadow-lg"}>
                <span className="flex items-center gap-2">
                  {albumLoading
                    ? <Loader2 className="w-4 h-4 animate-spin" />
                    : <Images className="w-4 h-4" />}
                  {albumLoading ? "Loading…" : "View album"}
                </span>
              </button>
            )}
            <button onClick={startOver}
              className={"px-4 py-2 rounded-lg text-sm transition " +
                (dark ? "bg-ink-700 hover:bg-ink-600 text-slate-200"
                      : "bg-slate-100 hover:bg-slate-200 text-ink-900")}>
              Analyze another video
            </button>
          </div>

          {/* Post-album review panel */}
          {sid && (
            <ReviewPanel sessionId={sid} eventName={album?.event_name ?? file?.name ?? "Event"} />
          )}
        </div>
      )}

      {/* Error */}
      {phase === "error" && (
        <div className="text-center py-3">
          <AlertTriangle className="w-12 h-12 mx-auto mb-3 text-rose-500" />
          <div className="text-rose-700 font-medium">Couldn't analyze the video</div>
          <pre className={"text-xs mt-2 whitespace-pre-wrap " + subTextCls}>
            {error}
          </pre>
          <button onClick={() => { setPhase("idle"); setError(null); }}
            className={"mt-3 px-4 py-2 rounded-lg text-sm transition " +
              (dark ? "bg-ink-700 hover:bg-ink-600 text-slate-200"
                    : "bg-slate-100 hover:bg-slate-200 text-ink-900")}>
            Try again
          </button>
        </div>
      )}
    </div>
  );
}


function UploadProgress(
  { label, subtitle, pct, dark }:
  { label: string; subtitle: string; pct: number; dark: boolean }
) {
  return (
    <div className="py-2">
      <div className="flex items-center gap-3 mb-3">
        <Loader2 className="w-5 h-5 animate-spin text-brand-500" />
        <div className="flex-1">
          <div className={"font-medium " +
            (dark ? "text-slate-100" : "text-ink-900")}>{label}</div>
          <div className={"text-xs " +
            (dark ? "text-slate-400" : "text-slate-500")}>{subtitle}</div>
        </div>
        <div className={"font-mono text-sm " +
          (dark ? "text-brand-400" : "text-brand-600")}>{pct}%</div>
      </div>
      <div className={"h-2 rounded-full overflow-hidden " +
                       (dark ? "bg-ink-700" : "bg-slate-100")}>
        <div className="h-full bg-gradient-to-r from-brand-500 to-rose-500
                        transition-all duration-300"
          style={{ width: `${pct}%` }} />
      </div>
    </div>
  );
}
